### ISSUE TITLE
Formatting turns with incomplete info should raise error

### ISSUE THREAD

**Issue by RSTZZZ** [McGill-NLP/weblinx#19]
Example: Formatting a turn with intent of `click` where element is `None`.  During prediction, the element predicted could also be `None`. 

Expected: Raise a formatting error / incorrect turn type 

Turn.element can be NoneType. If it is, we will get the error:
`'NoneType' object has no attribute 'get'`

https://github.com/McGill-NLP/weblinx/blob/47d6acc8cc721c23be48a02303bb56326ff77f69/weblinx/utils/format.py#L471

**Comment by xhluca** [comment]
I do not feel it would be useful to raise an error by default as that may break the code unexpectedly, which can be frustrating for users of the library. For example, certain elements like say actions will not have a UID. Instead, I would recommend adding an assertion in processing codes to ensure that this does not happen. Alternatively, you can just filter for such cases directly in the processing code. For example:

```python
# code to load turns here...
filtered_turns = list(filter(turns, lambda t: t.intent == "click" and t.element is not None))
# Continue using the turns
```

**Comment by RSTZZZ** [comment]
Currently this function is added as part of the formatter, found in this function: 

https://github.com/McGill-NLP/weblinx/blob/47d6acc8cc721c23be48a02303bb56326ff77f69/modeling/llama/processing.py#L22

```
def build_formatter_for_multichoice():
    format_click = partial(wlf.format_click, formatters=(wlf.format_uid,))
    format_text_input = partial(
        wlf.format_text_input,
        formatters=(
            partial(wlf.format_arg_item, name="text", max_length=200),
            wlf.format_uid,
        ),
    )
    format_change = partial(
        wlf.format_change,
        formatters=(
            partial(wlf.format_arg_item, name="value", max_length=200),
            wlf.format_uid,
        ),
    )
    format_submit = partial(wlf.format_submit, formatters=(wlf.format_uid,))
```

Currently, its only used to format `click`, `text_input`, `change` and `submit` where it expects to have the element in the `turn` object.  It wouldn't run on the intents such as `say`, `scroll` or `load`.  If you're using it for inference, the element may be `None`. In this case, there would be an error regardless, so raising an exception such as `Expected turn.element to exist`  would be clearer than seeing `'NoneType' object has no attribute 'get'`

**Comment by xhluca** [comment]
I think this may affect some of the current pipeline if an error is raised, as it would currently fail. This means there's a small number of cases where the prediction is `uid=None`; I just checked and it seems less than 1% of the data is affected by this issue, but they are cleaned up post-hoc here so eval is actually never affected by the uid=None issue: https://github.com/McGill-NLP/weblinx/blob/47d6acc8cc721c23be48a02303bb56326ff77f69/weblinx/eval/__init__.py#L83C5-L133

The pipeline is currently set up in a way that if we raise the exception, it would break current and future code using `build_formatter_for_multichoice`, even if it doesn't affect the resulting evaluation score. This would be messy as it'd be 3-level deep into the code. There's two ways this could be solved:
1. Use `throw_error=False` argument, that is false by default, and for your current use case it would be set to True. By choosing false by default, it would allow the existing pipeline to work, but for your inference use case it would give clear error.
2. Refactor the `modeling/*/processing.py` codebase (LLaMA, DMR, I have a few more I want to release given enough bandwidth which will also need the same treatment) such that this error would not break the way the code is currently set up.

I would suggest going with (1) for now to unblock you from your use case, then once (2) is implemented we can set the throw_error=True by default. [Here's an example](https://github.com/McGill-NLP/weblinx/blob/47d6acc8cc721c23be48a02303bb56326ff77f69/weblinx/__init__.py#L853).

Feel free to open a PR for 1 whenever you wish, as well as 2 (though that one might be more time consuming since it'd require rerunning the training and eval code which may take a few hours).

**Comment by RSTZZZ** [comment]
I was thinking along the lines of this:

```
def format_uid(turn, uid_key="data-webtasks-id", return_as="dict"):

    if (not turn.element):
        raise ValueError("Expected element to be not None for this turn.")

    output = {"uid": turn.element.get("attributes", {}).get(uid_key, None)}

    return format_output_dictionary(output, return_as=return_as)
```

This wouldn't impact any code that calls this function since instead of getting the non-descriptive error of `'NoneType' object has no attribute 'get'`, we're getting the more descriptive error `Expected element to be not None for this turn.`.

**Comment by xhluca** [comment]
@RSTZZZ I think I understand what you mean now. Can you verify if this fixes your issue? https://github.com/McGill-NLP/weblinx/pull/23
