### ISSUE TITLE
I have discovered an inconsistency between the screenshot and the html rendering.

### ISSUE THREAD

**Issue by miyapeng** [McGill-NLP/weblinx#21]
When I was processing the data, I visualized the bbox of each screenshot onto the image, as shown in Figure 1. I found that the bbox of some actions did not correctly correspond to the screenshot. At this point, I referred to the display at https://huggingface.co/spaces/McGill-NLP/weblinx-explorer?recording=aajfwoq and found that the screenshot in the dataset was not correct. I also rendered the corresponding HTML and found that the rendering of the HTML was not consistent with the screenshot, as shown in Figure 2. The examples I examined were #10 and #11 in aajfwoq.
![Figure1](https://github.com/McGill-NLP/weblinx/assets/94541811/801f1831-2da5-4dc5-85d4-f6eba1fe9f53)
![Figure2](https://github.com/McGill-NLP/weblinx/assets/94541811/d7b3a2f7-0826-4460-b1d0-ae4406b2a7a2)

Can you fix the errors in datasets? thank you.

**Comment by xhluca** [comment]
It is possible that some screenshots are delayed due to how Chrome screenshot mechanism works: it can only take a limited number of screenshots per second, so there might be a delay of a few hundred milliseconds between the real html and the screenshot. During the validation process, we fixed most of the cases where this would happen; however, it is possible that a small number of cases (probably around 5%) where the discrepancy was not identified.

For those cases, feel free to use this form to identify them; we will do our best to fix them in the next version of this dataset: https://forms.gle/hjcwpkP5T2fVe7T99

In the meantime, please feel free to directly render the HTMLs as you suggested to generate the screenshots (if you have a nice script, feel free to share it in discussions!), or use the mp4 videos (they are located on [huggingface dataset](https://huggingface.co/datasets/McGill-NLP/WebLINX-full/tree/main/demonstrations/)). For videos, please note that the cursor might pose an issue.

**Comment by miyapeng** [comment]
Thank you for answerig me. But I have on access to the form(https://forms.gle/hjcwpkP5T2fVe7T99).
![image](https://github.com/McGill-NLP/weblinx/assets/94541811/7f400f04-f5ba-4cb0-a01e-c37d966a9cb6)

**Comment by xhluca** [comment]
Sorry I updated the permission. Please try this link: https://forms.gle/UvYDeAnoAGhGAzdCA

**Comment by xhluca** [comment]
@miyapeng let me know if this link worked.

**Comment by xhluca** [comment]
I tested it with a private browser and seems it works. Please reopen this issue if there's anything else to discuss.

**Comment by miyapeng** [comment]
Apologies for my delayed response, and thank you. I can open the link. We are planning to use your dataset for a project involving a screen agent, so we are eagerly awaiting the latest version of your dataset with the corrected errors

**Comment by xhluca** [comment]
@miyapeng There's a few improvements and additional features we have in mind, so it might take some time before we release the updated version. In the mean time, I recommend the [previously mentioned options](https://github.com/McGill-NLP/weblinx/issues/21#issuecomment-2033219207): Using video frames from the recordings (be careful of mouse cursor), re-rendering the screenshots (as you showed above, for automation you could probably use selenium).
